"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var hobbies = [
    "cooking",
    "baking",
    "grilling",
    "food styling",
    "meal prepping",
    "cake decorating",
    "home brewing",
    "cheese making",
    "tasting",
    "drawing",
    "painting",
    "sculpting",
    "calligraphy",
    "pottery",
    "graphic design",
    "origami",
    "crafting",
    "jewelry making",
    "woodworking",
    "embroidery",
    "kritting",
    "collage making",
    "glassblowing",
    "mosaic art",
    "digital art",
    "printmaking",
    "cartooning",
    "street art",
    'ballet',
    'hip-hop',
    'ballroom dancing',
    'comtemporary dancing',
    'jazz dance',
    'tap dancing',
    'salsa dancing',
    'breakdancing',
    'belly dancing',
    'flamenco',
    'swing dancing',
    'tango',
    'folk dancing',
    'pole dancing',
    'irish dancing',
    'bhangra',
    'capoeira',
    'bollywood dancing',
    'zumba',
    'street dance',
    'kizomba',
    'polynesian dancing',
    'esports',
    'rpgs games',
    'fps games',
    'moba games',
    'stragery games',
    'sandbox games',
    'adventure games',
    'simulation games',
    'puzzle games',
    'fighting games',
    'platformer games',
    'racing games',
    'stealth games',
    'open-world games',
    'battle royale games',
    'mmorpg',
    'survival games',
    'indie games',
    'virtual reality games',
    'roguelike games',
    'co-op games',
    'gardening',
    'planting',
    'pruning',
    'watering',
    'composting',
    'harvesting',
    'landscaping',
    'mulching',
    'potting',
    'weeding',
    'transplanting',
    'fertilizing',
    'singing',
    'guitar',
    'piano',
    'violin',
    'drums',
    'bass guitar',
    'songwriting',
    'music theory',
    'flute',
    'saxophone',
    'choir',
    'trumpet',
    'cello',
    'harp',
    'clarinet',
    'banjo',
    'ukulele',
    'music production',
    'bagpipes',
    'accordion',
    'xylophone',
    'oboe',
    'recorder',
    'tuba',
    'camping',
    'fishing',
    'picknicking',
    'rock climbing',
    'nature walks',
    'zip lining',
    'paragliding',
    'biking',
    'mountaineering',
    'metal detecting',
    'party',
    'bar hopping',
    'restaurant',
    'concert',
    'festival',
    'night club',
    'cinema',
    'karaoke',
    'photography',
    'camera',
    'exposure',
    'portrait photography',
    'landscape photography',
    'composition',
    'book',
    'novel',
    'fiction',
    'non-fiction',
    'bestseller',
    'paperback',
    'e-book',
    'audiobook',
    'mystery',
    'biography',
    'science fiction',
    'poetry',
    'fantasy',
    'memoir',
    'classic literature',
    'manga',
    'football',
    'basketball',
    'tennis',
    'swimming',
    'running',
    'cycling',
    'volleyball',
    'gymnastics',
    'martial arts',
    'rugby',
    'golf',
    'skiing',
    'surfing',
    'climbing',
    'snowboarding',
    'skateboarding',
    'archery',
    'horseback riding',
    'table tennis',
    'badminton',
    'fencing',
    'kayaking',
    'canoeing',
    'windsurfing',
    'judo',
    'triathlon',
    'sailing',
    'parkour',
    'rafting',
    'karate',
    'taekwondo',
    'traveling',
    'backpacking',
    'sightseeing',
    'adventure',
    'culture',
    'exploration',
    'solo travel',
    'hiking',
    'road trip',
    'souvenir collecting',
    'urban exploration',
    'creative writing',
    'journaling',
    'blogging',
    'scriptwriting',
    'letter writing',
    'songwriting',
    'copywriting',
    'technical writing',
    'poetry writing',
    'fiction writing',
    'travel writing',
    'content writing',
];
exports.default = hobbies;
